### PR TITLE
Adds requested changes to receipt messages.

### PR DESCRIPTION
**Pull request by mango-habanero**
This pull request implements the requested amendment on the token send receipt messages as requested in the issue below:
https://github.com/GrassrootsEconomics/CIC-Docs/issues/104
It also defaults to displaying a user's phone number in the event that their name information is not set.

### CODE REVIEW

**Review by nolash — COMMENTED** [review]
Is this interpolation hit by a test at all?

**Review by WillRuddick — DISMISSED** [review]
looks good!

**Comment by mango-habanero** [comment]
> Is this interpolation hit by a test at all?

Seems like it isn't

**Comment by nolash** [comment]
@PhilipWafula will you add please? thanks

**Review by WillRuddick — APPROVED** [review]

**Pull request merged**
