### PR TITLE
Trims message length

### PR DESCRIPTION
**Pull request by mango-habanero**
This pull request is a quickfix to reduce the length of SMS to a value below 160 characters to reduce the cost per SMS .

https://gitlab.com/grassrootseconomics/cic-platform-temp/-/issues/18

### CODE REVIEW

**Review by nolash — COMMENTED** [review]
Not sure if I get it - this is 2 chars less? How can this exceed 160 in any case? Do you need the word "Successfully"?

**Comment by mango-habanero** [comment]
> Not sure if I get it - this is 2 chars less? How can this exceed 160 in any case? Do you need the word "Successfully"?

@nolash my work here relies heavily on this example:
[](https://gitlab.com/grassrootseconomics/cic-platform-temp/-/issues/18)
However, to answer your question I think the injected data is what increases the character length.

>Do you need the word "Successfully"?

I think its important because it the key word that signifies the transfer was actually completed.

Your question also just made me realize the lengths of the recipient's and sender's names will affect the number of characters here so it may be worth reviewing.
@WillRuddick could you please chime in here ?

**Review by nolash — APPROVED** [review]
Not sure if I get it - this is 2 chars less? How can this exceed 160 in any case? Do you need the word "Successfully"?

**Comment by nolash** [comment]
> Not sure if I get it - this is 2 chars less? How can this exceed 160 in any case? Do you need the word "Successfully"?

apparently it somehow copied the text in my approval. dunno why. ignore this latter comment please.

**Pull request merged**
