### PR TITLE
Updates for local dev environment

### PR DESCRIPTION
**Pull request by BenSchZA**
@nolash onboarded me into the current state of the local dev environment. We made a few small changes to the `local_config.ini` file, namely:

1. `tfa_required_roles` to avoid QR code
2. `valid_service_code` added (I think this may already be on @nolash 's branch)

### CODE REVIEW

**Review by nolash — DISMISSED** [review]

**Comment by nolash** [comment]
@BenSchZA hang on I was a bit quick there;

see the current `staging_config.ini` for the correct ussd service code. it is needed because tests are also being made there with real phones sometimes.

**Comment by nolash** [comment]
If I'm not mistaken it's `*483*061#` @WillRuddick can you verify?

**Review by nolash — DISMISSED** [review]
so just change that please and its good to go.

**Comment by BenSchZA** [comment]
> so just change that please and its good to go.

@nolash Just made the update, requires a new approval.

**Review by nolash — APPROVED** [review]

**Pull request merged**
